# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Daily updates for critical internal packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@fairmint/canton-node-sdk'
      - dependency-name: '@fairmint/open-captable-protocol-daml-js'

  # Weekly updates for all other npm packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@fairmint/canton-node-sdk'
      - dependency-name: '@fairmint/open-captable-protocol-daml-js'
